name: DLCv3-WebUI
channels:
  - nvidia/label/cuda-12.4.1 # For cuda-toolkit
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cuda-toolkit # Sourced from nvidia/label/cuda-12.4.1 channel
  - pytables=3.8.0 # Sourced from conda-forge channel
  - ffmpeg # For video processing, sourced from conda-forge
  - git # For pip installing from git
  - pip
  - pip:
    - -r requirements.txt 